module(
    name = "ecommerce",
    version = "0.1.0",
)
#used to create, mutate, and manage tar archives within the Bazel build system
bazel_dep(name = "tar.bzl", version = "0.10.7")
#high-performance Bazel ruleset for running Node.js tools and building JavaScript/TypeScript projects
bazel_dep(name = "aspect_rules_js", version = "3.3.1")
#high-performance Bazel ruleset for TypeScript compilation
bazel_dep(name = "aspect_rules_ts", version = "3.9.2")
# bazel is written using Starlark, standard library of common Starlark functions
bazel_dep(name = "bazel_skylib", version = "1.9.2")
# high-performance Bazel ruleset designed to compile JavaScript and TypeScript files using the Rust-based SWC (Speedy Web Compiler)
bazel_dep(name = "aspect_rules_swc", version = "2.7.6")

