module(
    name = "ecommerce",
    version = "0.1.0",
)
#used to create, mutate, and manage tar archives within the Bazel build system
bazel_dep(name = "tar.bzl", version = "0.10.7")
#high-performance Bazel ruleset for running Node.js tools and building JavaScript/TypeScript projects
bazel_dep(name = "aspect_rules_js", version = "3.3.1")
#high-performance Bazel ruleset for TypeScript compilation
bazel_dep(name = "aspect_rules_ts", version = "3.9.2")
# bazel is written using Starlark, standard library of common Starlark functions
bazel_dep(name = "bazel_skylib", version = "1.9.2")
# high-performance Bazel ruleset designed to compile JavaScript and TypeScript files using the Rust-based SWC (Speedy Web Compiler)
bazel_dep(name = "aspect_rules_swc", version = "2.7.6")
# foundation ruleset for running Node.js, JavaScript, and TypeScript tools inside Bazel.
bazel_dep(name = "rules_nodejs", version = "6.7.5")

#  bridge between the Node.js ecosystem (PNPM) and the Bazel build system.
#loads a special script called a Module Extension from the aspect_rules_js ruleset.
npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
#runs the parsing engine on your lockfile.
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
)
#exposes the newly generated @npm repository to the rest of your local project.
use_repo(npm, "npm")


rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext")
rules_ts_ext.deps(
    ts_version_from = "//gateway:package.json",
)
use_repo(rules_ts_ext, "npm_typescript")
bazel_dep(name = "aspect_rules_lint", version = "2.7.2")
# Java
bazel_dep(name = "rules_java", version = "9.7.0")
bazel_dep(name = "rules_jvm_external", version = "7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.springframework.boot:spring-boot:3.3.2",
        "org.springframework.boot:spring-boot-autoconfigure:3.3.2", # Provides @SpringBootApplication
        "org.springframework.boot:spring-boot-starter-web:3.3.2",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    known_contributing_modules = ["protobuf"],
)
use_repo(maven, "maven")