load("@npm//:defs.bzl", "npm_link_all_packages")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@aspect_rules_swc//swc:defs.bzl", "swc")

npm_link_all_packages(name = "node_modules")

ts_project(
    name = "gateway_ts",
    srcs = glob(["src/**/*.ts"]),
    tsconfig = "tsconfig.json",
    root_dir = "src",
    out_dir = "dist",
    transpiler = swc,
    validate = False,
    deps = [
        ":node_modules/express",
    ],
)

js_binary(
    name = "gateway",
    entry_point = ":gateway_ts",
    data = [":gateway_ts", "package.json"],
    visibility = ["//:all_services"],
)
