load("@aspect_rules_js//js:defs.bzl", "js_binary", "js_test")
load("@aspect_rules_swc//swc:defs.bzl", "swc")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

ts_project(
    name = "index_ts",
    srcs = ["src/index.ts"],
    out_dir = "dist",
    root_dir = "src",
    transpiler = swc,
    tsconfig = "tsconfig.json",
    validate = False,
    deps = [
        ":node_modules/cors",
        ":node_modules/express",
        ":node_modules/helmet",
        ":node_modules/http-proxy-middleware",
        ":node_modules/morgan",
        ":utils_ts",
    ],
)

js_binary(
    name = "gateway",
    data = [
        "package.json",
        ":index_ts",
    ],
    entry_point = ":index_ts",
    visibility = ["//:all_services"],
)

ts_project(
    name = "utils_ts",
    srcs = glob(["src/utils/**/*.ts"]),
    out_dir = "dist",
    root_dir = "src",
    transpiler = swc,
    tsconfig = "tsconfig.json",
    validate = False,
)

js_test(
    name = "services_test",
    data = [":utils_ts"],
    entry_point = "src/utils/services.test.js",
    visibility = ["//visibility:private"],
)

js_test(
    name = "rate_limiter_test",
    data = [":utils_ts"],
    entry_point = "src/utils/rate-limiter.test.js",
    visibility = ["//visibility:private"],
)

test_suite(
    name = "tests",
    tests = [
        ":services_test",
        ":rate_limiter_test",
    ],
)
